import type { CrawlRow } from './types.js';

/** Ligne de crawl « saine » par défaut ; chaque test ne précise que ce qu'il teste. */
export function makeRow(overrides: Partial<CrawlRow> = {}): CrawlRow {
  return {
    site_key: 'test',
    page_id: null,
    url: 'https://example.fr/page',
    slug: 'page',
    expected_state: 'indexable',
    http_status: 200,
    final_url: 'https://example.fr/page',
    redirect_chain: [],
    response_ms: 100,
    indexable: true,
    robots_txt_allowed: true,
    meta_robots: null,
    canonical: 'https://example.fr/page',
    title: 'Titre',
    meta_description: 'Description',
    h1: 'H1',
    h1_count: 1,
    h2_count: 3,
    structured_data: ['LocalBusiness'],
    word_count: 900,
    content_hash: 'abc',
    content_extract: null,
    links_out: 5,
    links_in: 2,
    click_depth: 1,
    in_sitemap: true,
    gsc_verdict: null,
    gsc_coverage_state: null,
    gsc_indexing_state: null,
    gsc_page_fetch_state: null,
    gsc_robots_state: null,
    gsc_google_canonical: null,
    gsc_last_crawl: null,
    gsc_inspected_at: null,
    funnel_stage: '',
    issues: [],
    impressions28: 0,
    ...overrides,
  };
}
